"use client";

import { useState } from "react";
import { FinancePanel } from "@/components/cards";
import { CallShell } from "@/components/shells/CallShell";
import fixtures from "@/lib/fixtures/snapshots.json";
import type { FinanceSnapshot } from "@/lib/finance";
import styles from "./preview.module.css";

/**
 * The cards, driven by recorded planner output instead of a phone call.
 *
 * The fixtures in `snapshots.json` are generated by the real planner (see the
 * script in docs/build-log.md), so this page shows exactly what a call would
 * produce — and it can be opened, changed and eyeballed in a second rather
 * than in a forty-second conversation.
 *
 * "In the call" renders the real CallShell around them, which is the only way
 * to check the split layout and the phone tabs without booking a Daily room.
 */

const CASES: { key: keyof typeof fixtures; label: string; blurb: string }[] = [
  {
    key: "early",
    label: "Mid-conversation",
    blurb: "A balance and two bills. No plan asked for yet.",
  },
  {
    key: "tight",
    label: "Tight but solvable",
    blurb: "Salary lands after the rent. Works, once two things are put off.",
  },
  {
    key: "unsolvable",
    label: "Does not balance",
    blurb: "Nothing left to cut. The gap is stated, not dressed up.",
  },
];

export default function PreviewPage() {
  const [active, setActive] = useState<keyof typeof fixtures>("tight");
  const [inCall, setInCall] = useState(false);
  const snapshot = fixtures[active] as unknown as FinanceSnapshot;
  const blurb = CASES.find((entry) => entry.key === active)?.blurb;

  if (inCall) {
    return (
      <>
        <CallShell
          elapsedSeconds={187}
          muted={false}
          agentSpeaking={false}
          userSpeaking={false}
          thinking={false}
          transcript={[]}
          finance={snapshot}
          connectionLabel="Preview"
          onMute={() => {}}
          onEnd={() => setInCall(false)}
        />
        <button
          type="button"
          onClick={() => setInCall(false)}
          className={styles.escape}
        >
          Back to cards
        </button>
      </>
    );
  }

  return (
    <main className={styles.page}>
      <header className={styles.head}>
        <h1 className={styles.title}>Card preview</h1>
        <div className={styles.tabs}>
          {CASES.map((entry) => (
            <button
              key={entry.key}
              type="button"
              onClick={() => setActive(entry.key)}
              className={active === entry.key ? styles.tabOn : styles.tab}
            >
              {entry.label}
            </button>
          ))}
        </div>
        <p className={styles.blurb}>{blurb}</p>
        <button
          type="button"
          onClick={() => setInCall(true)}
          className={styles.tab}
        >
          See it in the call layout
        </button>
      </header>

      <div className={styles.stage}>
        <FinancePanel snapshot={snapshot} />
      </div>
    </main>
  );
}
